name: "Shangab SSH Sync"
description: "Syncs a repository folder to a remote server using SSH and rsync."
author: "Abubaker Shangab"
branding:
  color: "green"
  icon: "server"

inputs:
  ssh-public-key:
    description: "The public SSH key for authentication."
    required: true

  ssh-private-key:
    description: "The private SSH key for authentication."
    required: true
  
  remote-host:
    description: "The remote server hostname."
    required: true
  
  remote-user:
    description: "The remote server username."
    required: true
  
  user-password:
    description: "The remote server user password."
    required: true
 
  local-path:
    description: "The local folder path to sync."
    required: true
  remote-path:
    description: "The remote folder path to sync to."
    required: true

runs:
  using: "node12"
  main: "index.js"

outputs:
  success-message:
    description: "Successfully synced Local folder to Remote."
