#  Test current githib action project.

name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install NCC global
        run: npm install -g @vercel/ncc

      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Prepare SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      
      - uses: ./
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: ${{ secrets.REMOTE_USER }}
          local-path: './Test'
          remote-path: '/home/kwikrowc/public_html/shangab-ssh-sync'
